### ISSUE TITLE
groonga-query-log-run-regression-test is terminated unexpectedly.

### ISSUE THREAD

**Issue by kenhys** [groonga/groonga-query-log#2]
### Problem:

groonga-query-log-run-regression-test is terminated unexpectedly.

```
[[0,1473327504.548014,255.6547722816467],true]
/usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-1.2.7/lib/groonga/command/base.rb:90:in `initialize': undefined method `command_name' for Groonga::Command::Base:Class (NoMethodError)
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:308:in `new'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:308:in `parse_uri_path'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:282:in `parse_command'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:250:in `parse_line'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:145:in `block in finish'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:144:in `catch'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:144:in `finish'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:118:in `consume_data'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:75:in `event_parse'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-command-parser-1.0.5/lib/groonga/command/parser.rb:46:in `parse'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/analyzer/statistic.rb:54:in `command'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/server-verifier.rb:51:in `block (2 levels) in run_producer'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/parser.rb:88:in `call'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/parser.rb:88:in `parse_line'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/parser.rb:54:in `block in parse'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/parser.rb:43:in `each_line'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/parser.rb:43:in `parse'
        from /usr/local/groonga_v20160909/lib/ruby/gems/2.2.0/gems/groonga-query-log-1.2.2/lib/groonga/query-log/server-verifier.rb:50:in `block in run_producer'
Running test against query log...: ./query-logs/query-2016051800.log
```

### How to reproduce

This error occurs when the following gem are used with:

groonga-query-log 1.2.2
groonga-command 1.2.7
groonga-command-parser 1.0.5

And query log contains "/" only. It seems groonga-command 1.2.3 or later is affected this problem.

### Workaround

Downgrade groonga-command to 1.2.1. 
but I want to use latest groonga-command.

**Comment by kenhys** [comment]
I've found a solution to fix this issue, but there may be more better one.

```
diff --git a/lib/groonga/query-log/server-verifier.rb b/lib/groonga/query-log/server-verifier.rb
index 1a16af0..0d4a236 100644
--- a/lib/groonga/query-log/server-verifier.rb
+++ b/lib/groonga/query-log/server-verifier.rb
@@ -48,6 +48,7 @@ module Groonga
         Thread.new do
           parser = Parser.new
           parser.parse(input) do |statistic|
+            next unless statistic.command
             next unless target_command?(statistic.command)
             @queue.push(statistic)
           end
diff --git a/lib/groonga/query-log/version.rb b/lib/groonga/query-log/version.rb
index b211519..3163fb8 100644
--- a/lib/groonga/query-log/version.rb
+++ b/lib/groonga/query-log/version.rb
@@ -16,6 +16,6 @@

 module Groonga
   module QueryLog
-    VERSION = "1.2.3"
+    VERSION = "1.2.2.1"
   end
 end

diff --git a/lib/groonga/command/parser.rb b/lib/groonga/command/parser.rb
index 25661e6..2daf04c 100644
--- a/lib/groonga/command/parser.rb
+++ b/lib/groonga/command/parser.rb
@@ -246,6 +246,8 @@ module Groonga
           # ignore empty line
         when /\A\#/
           on_comment($POSTMATCH)
+        when /\A\/\z/
+          # ignore / only line
         else
           @command = parse_command(line)
           @command.original_source = line
diff --git a/lib/groonga/command/parser/version.rb b/lib/groonga/command/parser/version.rb
index 37581ea..06d723c 100644
--- a/lib/groonga/command/parser/version.rb
+++ b/lib/groonga/command/parser/version.rb
@@ -19,7 +19,7 @@
 module Groonga
   module Command
     class Parser
-      VERSION = "1.0.6"
+      VERSION = "1.0.5.1"
     end
   end
 end
```

**Comment by kou** [comment]
Please show query log that reproduce this problem.

**Comment by kenhys** [comment]
Here is the typical query log. "/" doesn't contain any command information.

```
2016-05-18 00:00:19.227574|0x43a07f60|:000000034501000 drilldown(0)
2016-05-18 00:00:19.227628|0x43a07f60|<000000034554000 rc=0
2016-05-18 00:00:19.228848|0x4620bf60|>/
2016-05-18 00:00:19.228911|0x4620bf60|<000000000065000 rc=0
2016-05-18 00:00:19.234416|0x41203f60|:000000011775000 filter(60066)
2016-05-18 00:00:19.235641|0x41203f60|:000000013000000 filter(66662)
```

**Comment by kou** [comment]
Thanks.
